import React, { useState } from 'react';
import { useStore } from '../store/useStore';
import { Layout } from '../components/Layout';
import { Plus, Edit2, Trash2, Shield, AlertTriangle } from 'lucide-react';
import { Role, Permission } from '../types';

const PERMISSION_GROUPS = [
    {
        label: 'Ventas',
        permissions: [
            { id: 'sales:create', label: 'Crear Ventas' },
            { id: 'sales:read', label: 'Ver Historial' },
            { id: 'sales:cancel', label: 'Cancelar Ventas' }
        ]
    },
    {
        label: 'Inventario / Productos',
        permissions: [
            { id: 'products:read', label: 'Ver Productos' },
            { id: 'products:manage', label: 'Gestionar Productos (Crear/Editar/Eliminar)' }
        ]
    },
    {
        label: 'Clientes',
        permissions: [
            { id: 'clients:read', label: 'Ver Clientes' },
            { id: 'clients:manage', label: 'Gestionar Clientes' }
        ]
    },
    {
        label: 'Usuarios y Roles',
        permissions: [
            { id: 'users:manage', label: 'Gestionar Usuarios y Roles' }
        ]
    },
    {
        label: 'Finanzas y Reportes',
        permissions: [
            { id: 'reports:view', label: 'Ver Reportes Avanzados' },
            { id: 'cashflow:view', label: 'Ver Flujo de Caja' },
            { id: 'expenses:manage', label: 'Gestionar Gastos' }
        ]
    },
    {
        label: 'Sistema',
        permissions: [
            { id: 'settings:manage', label: 'Configuración General' },
            { id: '*', label: 'Acceso Total (Super Admin)' }
        ]
    }
];

export default function Roles() {
    const roles = useStore((state) => state.roles || []);
    const addRole = useStore((state) => state.addRole);
    const updateRole = useStore((state) => state.updateRole);
    const deleteRole = useStore((state) => state.deleteRole);

    const [isModalOpen, setIsModalOpen] = useState(false);
    const [editingRole, setEditingRole] = useState<Role | null>(null);
    const [formData, setFormData] = useState<{
        name: string;
        label: string;
        permissions: Permission[];
    }>({
        name: '',
        label: '',
        permissions: []
    });

    const handleOpenModal = (role?: Role) => {
        if (role) {
            setEditingRole(role);
            setFormData({
                name: role.name,
                label: role.label,
                permissions: role.permissions
            });
        } else {
            setEditingRole(null);
            setFormData({
                name: '',
                label: '',
                permissions: []
            });
        }
        setIsModalOpen(true);
    };

    const togglePermission = (permId: string) => {
        setFormData(prev => {
            const hasIt = prev.permissions.includes(permId as Permission);
            let newPermissions: Permission[];

            if (hasIt) {
                newPermissions = prev.permissions.filter(p => p !== permId);
            } else {
                newPermissions = [...prev.permissions, permId as Permission];
            }

            // Logic: If '*', clear others or keep them? Usually '*' overrides all.
            // If '*' is selected, maybe we just show that. 
            // For now, let's allow mixing but '*' implies everything check logic in app.

            return { ...prev, permissions: newPermissions };
        });
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        try {
            if (editingRole) {
                await updateRole(editingRole.id, formData);
            } else {
                // Auto-generate name/slug from label if empty or dirty
                const slug = formData.name || formData.label.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');

                await addRole({
                    id: '', // Generated by DB/Store
                    name: slug,
                    label: formData.label,
                    permissions: formData.permissions
                });
            }
            setIsModalOpen(false);
        } catch (error: any) {
            alert('Error al guardar el rol: ' + error.message);
        }
    };

    const handleDelete = async (id: string) => {
        if (confirm('¿Estás seguro de eliminar este rol? Los usuarios asignados podrían perder acceso.')) {
            await deleteRole(id);
        }
    };

    return (
        <Layout>
            <div className="h-[calc(100vh-8rem)] md:h-[calc(100vh-5rem)] flex flex-col">
                <div className="flex-none pb-4 bg-slate-50 flex justify-between items-center">
                    <div>
                        <h1 className="text-2xl font-bold text-slate-800 flex items-center gap-2">
                            <Shield className="w-6 h-6 text-primary-600" />
                            Roles y Permisos
                        </h1>
                        <p className="text-sm text-slate-500">Define qué pueden hacer los usuarios en el sistema.</p>
                    </div>

                    <button
                        onClick={() => handleOpenModal()}
                        className="bg-primary-600 text-white px-4 py-2 rounded-lg flex items-center gap-2 hover:bg-primary-700 transition-colors shadow-lg shadow-primary-500/30"
                    >
                        <Plus className="w-5 h-5" />
                        <span className="hidden sm:inline">Nuevo Rol</span>
                    </button>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 overflow-auto p-1">
                    {roles.map((role) => (
                        <div key={role.id} className="bg-white rounded-xl shadow-sm border border-slate-200 p-5 hover:shadow-md transition-shadow">
                            <div className="flex justify-between items-start mb-4">
                                <div>
                                    <h3 className="font-bold text-lg text-slate-800">{role.label}</h3>
                                    <span className="text-xs font-mono text-slate-400 bg-slate-100 px-1.5 py-0.5 rounded">
                                        {role.name}
                                    </span>
                                </div>
                                <div className="flex gap-1">
                                    <button
                                        onClick={() => handleOpenModal(role)}
                                        className="p-1.5 text-blue-600 hover:bg-blue-50 rounded transition-colors"
                                    >
                                        <Edit2 className="w-4 h-4" />
                                    </button>
                                    {role.name !== 'admin' && (
                                        <button
                                            onClick={() => handleDelete(role.id)}
                                            className="p-1.5 text-red-600 hover:bg-red-50 rounded transition-colors"
                                        >
                                            <Trash2 className="w-4 h-4" />
                                        </button>
                                    )}
                                </div>
                            </div>

                            <div className="space-y-3">
                                <div className="text-xs font-semibold text-slate-500 uppercase tracking-wider">
                                    Permisos ({role.permissions.includes('*') ? 'TOTAL' : role.permissions.length})
                                </div>
                                <div className="flex flex-wrap gap-2 max-h-32 overflow-y-auto scrollbar-thin scrollbar-thumb-slate-200 pr-2">
                                    {role.permissions.includes('*') ? (
                                        <span className="px-2 py-1 bg-purple-100 text-purple-700 rounded-md text-xs font-medium flex items-center gap-1">
                                            <Shield className="w-3 h-3" /> Acceso Total
                                        </span>
                                    ) : (
                                        role.permissions.map(p => {
                                            // Helper to find label
                                            let label: string = p;
                                            for (const g of PERMISSION_GROUPS) {
                                                const found = g.permissions.find(perm => perm.id === p);
                                                if (found) {
                                                    // Transform "Crear Ventas" (Actions) + Group Label (Page) -> "[Ventas - Crear]"
                                                    // Simplify for UI: Use a predefined mapping or construct it.
                                                    // Constructing: "[Group - Action]"
                                                    // E.g. Group "Ventas", Action "Crear Ventas" -> [Ventas - Crear Ventas]

                                                    // Let's make it cleaner as requested: [Ventas - Crear]
                                                    // We can strip common words or just use the Action label if it's descriptive enough, 
                                                    // but user asked for [Page - Action].
                                                    // Let's use the Group Label as "Page" and try to clean the Action label

                                                    const page = g.label.split(' / ')[0]; // "Inventario / Productos" -> "Inventario"
                                                    let action = found.label;

                                                    // Manual cleanups for brevity
                                                    action = action.replace('Crear ', '').replace('Ver ', '').replace('Gestionar ', '').replace(' (Super Admin)', '').replace(' (Crear/Editar/Eliminar)', '');
                                                    if (action === 'Historial') action = 'Leer';
                                                    if (action === 'Configuración General') action = 'Editar';
                                                    if (action === 'Acceso Total') action = 'Total';

                                                    // Re-map verbs if needed, or just use the cleaned noun?
                                                    // User example: [Ventas - Leer]
                                                    // My action for sales:read is "Ver Historial" -> "Historial" -> maybe "Leer"?
                                                    // Let's just Map ID to exact string user wants for best results.

                                                    const ID_TO_LABEL: Record<string, string> = {
                                                        'sales:create': 'Crear',
                                                        'sales:read': 'Leer',
                                                        'sales:cancel': 'Cancelar',
                                                        'products:read': 'Leer',
                                                        'products:manage': 'Crear/Editar',
                                                        'clients:read': 'Leer',
                                                        'clients:manage': 'Crear/Editar',
                                                        'users:manage': 'Gestionar',
                                                        'reports:view': 'Leer',
                                                        'cashflow:view': 'Leer',
                                                        'expenses:manage': 'Gestionar',
                                                        'settings:manage': 'Editar',
                                                        '*': 'Total'
                                                    };

                                                    action = ID_TO_LABEL[p as string] || action;
                                                    label = `[${page} - ${action}]`;
                                                }
                                            }

                                            return (
                                                <span key={p} className="px-2 py-1 bg-slate-100 text-slate-600 rounded-md text-xs border border-slate-200 font-mono">
                                                    {label}
                                                </span>
                                            );
                                        })
                                    )}
                                </div>
                            </div>
                        </div>
                    ))}

                    {roles.length === 0 && (
                        <div className="col-span-full p-10 text-center text-slate-400">
                            No se encontraron roles. Asegúrate de ejecutar el script de migración.
                        </div>
                    )}
                </div>

                {/* Modal */}
                {isModalOpen && (
                    <div className="fixed inset-0 bg-black/50 z-[60] flex items-center justify-center p-4 backdrop-blur-sm">
                        <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl max-h-[90vh] flex flex-col animate-in fade-in zoom-in duration-200">
                            <div className="p-6 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
                                <h2 className="text-xl font-bold text-slate-800 flex items-center gap-2">
                                    <Shield className="w-5 h-5 text-primary-600" />
                                    {editingRole ? 'Editar Rol' : 'Crear Nuevo Rol'}
                                </h2>
                                <button onClick={() => setIsModalOpen(false)} className="text-slate-400 hover:text-slate-600 text-2xl leading-none">
                                    &times;
                                </button>
                            </div>

                            <form onSubmit={handleSubmit} className="flex-1 overflow-hidden flex flex-col">
                                <div className="p-6 overflow-y-auto scrollbar-thin">
                                    <div className="grid grid-cols-2 gap-4 mb-6">
                                        <div>
                                            <label className="block text-sm font-medium text-slate-700 mb-1">Nombre Visible (Etiqueta)</label>
                                            <input
                                                type="text"
                                                required
                                                placeholder="Ej. Supervisor de Caja"
                                                value={formData.label}
                                                onChange={e => setFormData({ ...formData, label: e.target.value })}
                                                className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-primary-500 outline-none"
                                            />
                                        </div>
                                        <div>
                                            <label className="block text-sm font-medium text-slate-700 mb-1">Identificador (Slug)</label>
                                            <input
                                                type="text"
                                                placeholder="supervisor-caja"
                                                value={formData.name}
                                                // Only allow edit if not default roles? Or just let them be careful.
                                                // Assuming admin/seller are protected by logic, but editable here.
                                                onChange={e => setFormData({ ...formData, name: e.target.value })}
                                                className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-primary-500 outline-none bg-slate-50 font-mono text-sm"
                                            />
                                            <span className="text-[10px] text-slate-400">Dejar vacío para generar automático</span>
                                        </div>
                                    </div>

                                    <div className="space-y-6">
                                        <h3 className="font-semibold text-slate-700 border-b pb-2">Asignar Permisos</h3>

                                        {PERMISSION_GROUPS.map((group) => (
                                            <div key={group.label} className="bg-slate-50 p-4 rounded-lg border border-slate-100">
                                                <h4 className="text-sm font-bold text-slate-600 mb-3 uppercase tracking-wider">{group.label}</h4>
                                                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                                                    {group.permissions.map((perm) => (
                                                        <label key={perm.id} className="flex items-start gap-3 p-2 hover:bg-white rounded-md transition-colors cursor-pointer select-none">
                                                            <div className="relative flex items-center mt-0.5">
                                                                <input
                                                                    type="checkbox"
                                                                    checked={formData.permissions.includes(perm.id as Permission)}
                                                                    onChange={() => togglePermission(perm.id)}
                                                                    className="peer h-4 w-4 rounded border-slate-300 text-primary-600 focus:ring-primary-500"
                                                                />
                                                            </div>
                                                            <div className="text-sm">
                                                                <span className="font-medium text-slate-700 block">{perm.label}</span>
                                                                <span className="text-[10px] text-slate-400 font-mono">{perm.id}</span>
                                                            </div>
                                                        </label>
                                                    ))}
                                                </div>
                                            </div>
                                        ))}

                                        {formData.name === 'admin' && (
                                            <div className="p-4 bg-yellow-50 border border-yellow-200 rounded-lg text-sm text-yellow-800 flex items-start gap-2">
                                                <AlertTriangle className="w-5 h-5 shrink-0" />
                                                <p>Ten cuidado al editar el rol de Administrador. Se recomienda mantener el permiso "Acceso Total" (*).</p>
                                            </div>
                                        )}
                                    </div>
                                </div>

                                <div className="p-4 border-t border-slate-100 bg-slate-50 flex justify-end gap-3">
                                    <button
                                        type="button"
                                        onClick={() => setIsModalOpen(false)}
                                        className="px-4 py-2 text-slate-600 hover:bg-slate-100 rounded-lg transition-colors font-medium"
                                    >
                                        Cancelar
                                    </button>
                                    <button
                                        type="submit"
                                        className="px-6 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition-colors shadow-lg shadow-primary-500/30 font-bold"
                                    >
                                        Guardar Rol
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                )}
            </div>
        </Layout>
    );
}
